POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "how to ...",
    "author": "lee",
    "likes": 0,
    "url": "xxx"
}

### 
GET http://localhost:3003/api/blogs

###
PUT http://localhost:3001/api/notes/60f7ee9fff3cb629d872739a
Content-Type: application/json

{
    "content": "go is good",
    "important": "true"
}